/* ═══════════════════════════════════════════════════════════════════
   TRY BYTE TOOLS — shared data & helpers
   Auto-generated by admin.py — edit via the admin panel, not directly.
   Last updated: 2026-03-10 16:26:45
   ═══════════════════════════════════════════════════════════════════ */

const TBT_SETTINGS = {
  "email": "TryByteTools@gmail.com",
  "siteUrl": "https://trybytetools.github.io/TryByteTools/",
  "studioName": "Try Byte Tools",
  "tagline": "A small team that just wants to build cool stuff together."
};

const TBT_PIPELINE = [
  {
    "id": "pl1773173592454",
    "title": "Scene Sticky Notes",
    "type": "update",
    "version": "0.1.0",
    "desc": "Play in scene sticky notes 2D or 3D editors, helps organize and pass notes along to the team or maybe set notes up for next your coding session.",
    "patchNotesUrl": ""
  }
];

const TBT_PROJECTS = [
  {
    "id": "001",
    "title": "Folder Icons",
    "category": "unity",
    "tagLabel": "Unity Tool",
    "tagClass": "ptag-unity",
    "status": "wip",
    "author": "Dminx",
    "version": "1.0.0",
    "desc": "Right-click any folder in the Unity Project window to assign a custom color or icon. GUID-based persistence, zero runtime cost, easily import.",
    "patchNotes": [
      {
        "version": "0.9.9",
        "date": "2026-03-10",
        "notes": "Waiting on the release on Unity Asset Store."
      }
    ],
    "links": [
      {
        "label": "Asset Store",
        "href": "#",
        "icon": "store"
      }
    ]
  },
  {
    "id": "002",
    "title": "Scene Sticky Notes",
    "category": "unity",
    "tagLabel": "Unity Tool",
    "tagClass": "ptag-unity",
    "status": "wip",
    "author": "Dminx",
    "version": "0.1.0",
    "desc": "Play in scene sticky notes 2D or 3D editors, helps organize and pass notes along to the team or maybe set notes up for next your coding session.",
    "patchNotes": [
      {
        "version": "0.1.0",
        "date": "2026-03-10",
        "notes": "Created the sticky note package but it needs polishing. Wasn't sure what to say for the verison."
      }
    ],
    "links": []
  },
  {
    "id": "003",
    "title": "Unity Refresh Inspector Fix",
    "category": "unity",
    "tagLabel": "Unity Tool",
    "tagClass": "ptag-unity",
    "status": "live",
    "author": "Dminx",
    "version": "1.0.0",
    "desc": "This tool will fix an issue that is causing the inspector to not show which object or file you selected in the Unity Editor. Unity Version 6.3. This  works on Cosmic OS, it may work on other operating systems potentially.",
    "patchNotes": [
      {
        "version": "1.0.0",
        "date": "2026-03-10",
        "notes": "Uploaded"
      }
    ],
    "links": [
      {
        "label": "Github",
        "href": "#https://github.com/trybytetools/Unity-Inspector-Refresh-Fix-COSMIC-OS/tree/main",
        "icon": "store"
      }
    ]
  }
];

const TBT_TEAM = [
  {
    "id": "t001",
    "name": "Dminx",
    "role": "Solo Dev",
    "avatar": ""
  },
  {
    "id": "t1773173222505",
    "name": "Robix",
    "role": "Inspiration",
    "avatar": ""
  }
];

/* ─── Nav ─────────────────────────────────────────────────────────── */
function TBT_renderNav(activePage = 'home') {
  const pages = {
    home:      { href: 'index.html',      label: 'Home' },
    projects:  { href: 'projects.html',   label: 'Projects' },
    changelog: { href: 'changelog.html',  label: 'Changelog' },
  };
  const links = Object.entries(pages).map(([key, p]) =>
    `<li><a href="${p.href}"${key === activePage ? ' class="active"' : ''}>${p.label}</a></li>`
  ).join('');
  return `<nav id="main-nav">
    <a class="nav-logo" href="index.html">
      <div class="nav-logo-dot"></div>${TBT_SETTINGS.studioName || 'TRY BYTE TOOLS'}
    </a>
    <ul class="nav-links">
      ${links}
    </ul>
    <button class="nav-hamburger" id="nav-hamburger" aria-label="Open menu" aria-expanded="false">
      <span></span><span></span><span></span>
    </button>
  </nav>
  <div class="nav-drawer" id="nav-drawer" aria-hidden="true">
    <ul>${links}</ul>
  </div>
  <div class="nav-drawer-overlay" id="nav-drawer-overlay"></div>`;
}

/* ─── Footer ──────────────────────────────────────────────────────── */
function TBT_renderFooter() {
  const email = TBT_SETTINGS.email || 'TryByteTools@gmail.com';
  const name  = TBT_SETTINGS.studioName || 'Try Byte Tools';
  return `<footer>
    <span>© ${new Date().getFullYear()} <span class="blue">${name}</span>.</span>
    <nav class="footer-links">
      <a href="index.html">Home</a>
      <a href="projects.html">Projects</a>
      <a href="changelog.html">Changelog</a>
      <a href="mailto:${email}">Contact</a>
    </nav>
  </footer>`;
}

/* ─── Team renderer ───────────────────────────────────────────────── */
function TBT_renderTeam() {
  return TBT_TEAM.map(m => {
    const avatarContent = m.avatar
      ? `<img src="${m.avatar}" alt="${m.name}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;" />`
      : m.name.substring(0, 2).toUpperCase();
    return `
      <div class="team-card">
        <div class="team-avatar">${avatarContent}</div>
        <div>
          <div class="team-name">${m.name}</div>
          <div class="team-role">${m.role}</div>
        </div>
      </div>`;
  }).join('');
}

/* ─── Cursor ──────────────────────────────────────────────────────── */
function TBT_initCursor() {
  const cursor = document.getElementById('cursor');
  const ring   = document.getElementById('cursor-ring');
  if (!cursor || !ring) return;
  let mx = 0, my = 0, rx = 0, ry = 0;

  document.addEventListener('mousemove', e => {
    mx = e.clientX; my = e.clientY;
    cursor.style.left = mx + 'px'; cursor.style.top = my + 'px';
  }, { passive: true });

  (function animRing() {
    rx += (mx - rx) * 0.1; ry += (my - ry) * 0.1;
    ring.style.left = rx + 'px'; ring.style.top = ry + 'px';
    requestAnimationFrame(animRing);
  })();

  document.querySelectorAll('a, button').forEach(el => {
    el.addEventListener('mouseenter', () => {
      cursor.style.width = '14px'; cursor.style.height = '14px';
      ring.style.width = '48px'; ring.style.height = '48px';
      ring.style.borderColor = 'rgba(0,186,255,0.6)';
    });
    el.addEventListener('mouseleave', () => {
      cursor.style.width = '8px'; cursor.style.height = '8px';
      ring.style.width = '32px'; ring.style.height = '32px';
      ring.style.borderColor = 'rgba(61,158,255,0.45)';
    });
  });
}

/* ─── Scroll reveal ───────────────────────────────────────────────── */
function TBT_initReveal() {
  const obs = new IntersectionObserver(entries => {
    entries.forEach((e, i) => {
      if (e.isIntersecting) {
        setTimeout(() => e.target.classList.add('in'), i * 45);
        obs.unobserve(e.target);
      }
    });
  }, { threshold: 0.08 });
  document.querySelectorAll('.reveal').forEach(el => obs.observe(el));
}

/* ─── Card spotlight ──────────────────────────────────────────────── */
function TBT_initCardSpotlight() {
  document.querySelectorAll('.pcard').forEach(card => {
    card.addEventListener('mousemove', e => {
      const r = card.getBoundingClientRect();
      card.style.setProperty('--mx', ((e.clientX - r.left) / r.width  * 100) + '%');
      card.style.setProperty('--my', ((e.clientY - r.top)  / r.height * 100) + '%');
    });
  });
}

/* ─── Particle background ─────────────────────────────────────────── */
function TBT_initBackground(canvasId = 'bg-canvas') {
  const canvas = document.getElementById(canvasId);
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  let W, H, nodes = [];
  const NODE_COUNT = 80, MAX_DIST = 160;

  function resize() {
    W = canvas.width  = window.innerWidth;
    H = canvas.height = window.innerHeight;
    nodes = Array.from({ length: NODE_COUNT }, () => ({
      x:  Math.random() * W,
      y:  Math.random() * H,
      vx: (Math.random() - .5) * .22,
      vy: (Math.random() - .5) * .22,
      r:  Math.random() * 1.6 + 0.5,
      opacity: Math.random() * .5 + .2,
    }));
  }
  window.addEventListener('resize', resize, { passive: true });
  resize();

  requestAnimationFrame(function loop() {
    ctx.clearRect(0, 0, W, H);
    nodes.forEach(n => {
      n.x += n.vx; n.y += n.vy;
      if (n.x < 0 || n.x > W) n.vx *= -1;
      if (n.y < 0 || n.y > H) n.vy *= -1;
    });
    for (let i = 0; i < nodes.length; i++) {
      for (let j = i + 1; j < nodes.length; j++) {
        const a = nodes[i], b = nodes[j];
        const dx = a.x - b.x, dy = a.y - b.y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < MAX_DIST) {
          const alpha = (1 - dist / MAX_DIST) * .18;
          ctx.beginPath();
          ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y);
          ctx.strokeStyle = `rgba(61,158,255,${alpha})`;
          ctx.lineWidth = .7; ctx.stroke();
        }
      }
    }
    nodes.forEach(n => {
      ctx.beginPath();
      ctx.arc(n.x, n.y, n.r, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(0,186,255,${n.opacity})`; ctx.fill();
    });
    requestAnimationFrame(loop);
  });
}

/* ─── Mobile nav (hamburger + drawer) ────────────────────────────── */
function TBT_initMobileNav() {
  const hamburger = document.getElementById('nav-hamburger');
  const drawer    = document.getElementById('nav-drawer');
  const overlay   = document.getElementById('nav-drawer-overlay');
  if (!hamburger || !drawer) return;

  function setOpen(open) {
    hamburger.classList.toggle('open', open);
    hamburger.setAttribute('aria-expanded', String(open));
    drawer.classList.toggle('open', open);
    drawer.setAttribute('aria-hidden', String(!open));
    overlay.classList.toggle('open', open);
    document.body.style.overflow = open ? 'hidden' : '';
  }

  hamburger.addEventListener('click', () => setOpen(!drawer.classList.contains('open')));
  overlay.addEventListener('click',   () => setOpen(false));
  drawer.querySelectorAll('a').forEach(a => a.addEventListener('click', () => setOpen(false)));
  document.addEventListener('keydown', e => { if (e.key === 'Escape') setOpen(false); });
}

/* ─── Page transition ─────────────────────────────────────────────── */
function TBT_initPageTransition() {
  const overlay = document.getElementById('page-transition');
  if (!overlay) return;
  requestAnimationFrame(() => { overlay.style.opacity = '0'; });
  document.addEventListener('click', e => {
    const link = e.target.closest('a');
    if (!link) return;
    const href = link.getAttribute('href');
    if (!href || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('http') || link.target === '_blank') return;
    e.preventDefault();
    overlay.style.opacity = '1';
    setTimeout(() => { window.location.href = href; }, 380);
  }, true);
}
